### ISSUE TITLE
The manifest 'Templates.psd1" must contains a Extension section

### ISSUE THREAD

**Issue by LaurentDardenne** [roarwrecker/Templates#1]
Hi,
the manifest _templates.psd1_ must contains a [extension section](https://github.com/PowerShell/Plaster/tree/1e62113849f658b905c5b256537ecacd8ad1f967/examples/TemplateModule) inside the _PrivateData_ section.
Otherwise the Get-PlasterTemplate function do not retrieve the templates.

**Comment by roarwrecker** [comment]
Hi,
thanks for the hint.
